### ISSUE TITLE
Email someone when the database is down

### ISSUE THREAD

**Issue by sakibj** [oss/shrunk#62]

**Comment by jungsoo** [comment]
@sakibj lol was it down?

**Comment by sakibj** [comment]
No but if it goes down then an admin should get an email saying it's down so it can be fixed

**Comment by ksuarz** [comment]
I can help with this. We can do `mongostat` or have the Nagios plugin attempt it.

**Comment by richton** [comment]
+1 @ksuarz

A necessary component, but not the job of an application (i.e. Shrunk). 
It's the job of a monitoring system. Otherwise you get into a 
who-watches-the-watchers situation. It's basically a form of experimenter 
bias.

What IS Shrunk's (or any application's) job is to constantly maintain 
grace under pressure. i.e. if you turn the database off, does it still 
display beautifully, load (understandable error) pages reasonably quickly, 
write appropriate syslogs for forensics, etc etc. That would make a 
reasonable shrunk application feature request, if it doesn't do so 
already.

But as for determine if things are down, send email when things are down, 
call somebody with text-to-speech when things are down...that's a 
monitoring thing. Unless we need some hyper-specialized application-level 
(i.e. not system-level, not database-level, not protocol-level) monitoring 
I'm not sure what would really land here..."monitor mongo" is far from 
application-level though, it's database-level.

So "Email someone when the database is down" isn't really coding, it's 
more of a task (no code writing desirable) for the site's monitoring 
systems. For details on the Rutgers-specific implementation of monitoring, 
which isn't really relevant to the open-source application record, please 
see me or somebody nearby.

**Comment by mrjackchen-css** [comment]
I can see where this is a good hook to have for some, but we're 
currently monitoring mongod with nagios (which emails/texts us when it's 
down).

On 09/16/2015 05:43 PM, Sakib Jalal wrote:
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/oss/shrunk/issues/62
>

-- 
  Jack C. Chen
  OIT-EM System Administrator            office: Hill 146
  email: jcc@rutgers.edu			phone:  (848) 445-3995

**Comment by jungsoo** [comment]
So... this is already being done? Can we close this issue already?

**Comment by mrjackchen-css** [comment]
Yes, this is already being done externally.  I'm all for closing this issue.
